### PR TITLE
Move Go files to subfolder for cleaner import path.

### PR DESCRIPTION
**Pull request by lithammer**
Unfortunately this isn't backwards compatible even though it's trivial to fix for a user.

### CODE REVIEW

**Comment by GeertJohan** [comment]
So why do it? How does it make the import path cleaner?

**Comment by GeertJohan** [comment]
You can already to `import "github.com/renstrom/go-jump-consistent-hash"` (no import alias).

**Comment by lithammer** [comment]
> So why do it?

I probably won't, that's why I put it in a pull request. I know Gophers aren't big fans of backwards incompatible changes, just testing the water...

> You can already to `import "github.com/renstrom/go-jump-consistent-hash"` (no import alias).

Sure but it's not immediately obvious from that import path what the package name is, which is what I disliked about it. You have to either check the docs/readme or read the code. which to be fair, most probably will do (at least the readme).

**Comment by GeertJohan** [comment]
Ah yes. And the repository name is indeed a bit unfortunate. I've opened #3 as an alternative solution to this that is backwards compatible.

**Comment by lithammer** [comment]
It's also true for the other way around. If you come across `jump.Hash(a, b)` in some file it's not obvious it belongs to `github.com/renstrom/go-jump-consistent-hash` (unless using an alias like I did in the readme) even though it probably won't take much effort or time to figure out it still has _some_ cognitive overhead.

**Comment by GeertJohan** [comment]
Totally agree, that's why I think #3 is a good solution. Although I have not checked cross-platform compatibility. (!)

**Comment by lithammer** [comment]
I'm gonna have to let this sink in a little. To be honest, I would love to strip the "go-" part from the URL as well (thinking of [this tweet](https://twitter.com/rob_pike/status/618357610287226880) by Rob Pike), but that would probably mess up more things than what this pull request does. My dream:

``` go
import github.com/renstrom/jump-consistent-hash/jump
```

I wonder how many are _actually_ using this library...? I mean, better make breaking changes early on.

**Comment by lithammer** [comment]
A [search](https://github.com/search?q=github.com%2Frenstrom%2Fgo-jump-consistent-hash&type=Code&utf8=✓) for the import on GitHub reveals no uses. That doesn't mean private projects don't use it though.

**Pull request closed without merging**
